# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-07 15:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=10)),
                ('profile_picture', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('dob', models.DateField(null=True)),
                ('roll_no', models.PositiveIntegerField(max_length=10)),
                ('dept', models.CharField(max_length=50)),
                ('hostel', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
